### ISSUE TITLE
Chameleon makes FF 63 hang (linux)

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#103] opened 2018-11-17 17:11 UTC
As per title I noticed that chameleon seems to cause FF63 (on linux) to hang randomly, possibly due to heavy loading pages. I have 12gb of ram and  never experienced this behaviour before. Disabling chameleon solves the issue.

Another extension,decentraleyes, caused problems with FF63 on linux, as you can see there: https://git.synz.io/Synzvato/decentraleyes/issues/323.

Decentraleyes slows downs FF whereas chameleon seems to cause random hangs. FF63 introduces "WebExtensions now run in their own process on Linux" and one user in the link speculated it could be the reason behind such problem.

Do you think chameleon could be affected as well?

**Comment by sereneblue** [comment] 2018-11-17 20:49
What options have you enabled? Perhaps it's one of the script injection options causing problems.

**Comment by WPFilmmaker** [comment] 2018-11-18 00:36
@sereneblue Thanks for the reply. I have spoof audio context, which added recently, so it could be the culprit mmm. Timezone I think needs injection too but never gave me problems.

**Comment by WPFilmmaker** [comment] 2018-11-20 18:43
Update, no idea if it is related...seems that Noscript is often cited as cause for FF hanging...I have no idea if chameleon uses its own process but FF63 definitively caused problems to many Linux users.

**Comment by sereneblue** [comment] 2018-11-21 00:36
Can you test with a clean Firefox profile with only Chameleon running? How frequent is Firefox crashing for you? Perhaps the issue is fixed with FF64?

**Comment by sereneblue** [comment] 2018-11-22 17:02
Sure, I'll leave this issue open. You can try using the Developer or Beta edition of Firefox, they're both a version ahead of the regular release. If not, the next version of FF will be released on 12/11.

**Comment by sereneblue** [comment] 2018-12-15 03:50
@WPFilmmaker Are you experiencing issues with FF64?

**Comment by WPFilmmaker** [comment] 2018-12-15 13:52
@sereneblue The hangs are not present on FF64, just for references only decentraleyes still cause a few milliseconds of lag. No idea what they changed but it fixed the issue, you can close the ticket ;)

**Closed** 2018-12-15 19:49 UTC
