### ISSUE TITLE
Chameleon breaks Google Drive

### ISSUE THREAD

**Issue by thelmexx** [sereneblue/chameleon#356] opened 2020-05-04 07:55 UTC
## Expected Behavior
Google Drive (drive.google.com) working correctly, able to navigate folders and open documents.

## Current Behavior

Unable to leftclick on folders to open them, nor leftclick on document to open them. Disabling the addon and refreshing the page fixes this.

## Relevant settings
[(1)](https://feen.us/24qcgrx4ce.png)  [(2)](https://feen.us/0vt82845fc.png)  [(3)](https://feen.us/47ivnoq005.png)  [(4)](https://feen.us/58olul89p2.png)

## Context (Environment)
Windows 10 64-bit 1903, Firefox 75.0

**Comment by sereneblue** [comment] 2020-05-05 03:54
Hi @thelmexx,

I'm not able to replicate this bug, however, v0.20.3 may have resolved your issue. Please let me know if you're still experiencing issues after updating.

**Comment by thelmexx** [comment] 2020-05-06 07:14
Still happening as of v0.20.3, including with all other addons disabled. Specifically I can't navigate between folders and files on the drive interface, while I can still use side menus, e.g the trash menu.

**Comment by ck9ine** [comment] 2020-05-07 23:58
Had the same issue. Basically, one can log into Drive.  The navigation is present, as well as surrounding elements (around the all 4 edges of the page), however, the actual directory and/or file list would not appear.  Just blank -- in the middle of the page.  

I came to the conclusion that it was Chameleon after process of elimination with my addons.

Initially, I thought it might be related to enabled "Protect Window Name".  Wasn't it.

Luckily, I recalled the last thing I changed from the day or two before.  

Switching Timezone back to "Default" instead of a specific timezone fixed the issue for me.  Just switching the timezone back and forth, and then force refreshing the page, will instantly cause or fix the issue respectively.

**Comment by sereneblue** [comment] 2020-05-09 03:14
Thanks @ck9ine. That seems to be the cause of the issue. I've found where the issue is located but I'm not sure yet why it breaks.

**Comment by ck9ine** [comment] 2020-05-09 11:23
To add, the specific timezone I had chosen was my exact timezone (or maybe it was an hour off due to daylight savings).  Just in case one might think that it's some sort of IP/timezone validation check on Google's part.

**Comment by Keraldi** [comment] 2020-05-09 21:23
Opening google sheets with chameleon enabled (even if google is whitelisted) presents me with this error:
![Screenshot_20200509_231339](https://user-images.githubusercontent.com/23401986/81485076-e5de2e80-924a-11ea-9b89-fe88b103232c.png)
From top to bottom:  
'A Problem occurred. Reload.'  
'An error occurred on the server. Click on the reload-button in your browser to reload the page.'  
'File cannot be loaded. Try again or sent a bug report.'

https://docs.google.com/document/ works.
https://docs.google.com/spreadsheet/, ../presentations/ and ../forms/ sometimes work, reloading them a couple times fixes them if they don't work.

**Comment by sereneblue** [comment] 2020-05-10 05:09
@Keraldi That's interesting. Can you post your settings?

**Comment by Keraldi** [comment] 2020-05-10 06:11
https://gist.github.com/Keraldi/cbff5478436614261e17354718d5c539

I took the liberty of removing all rules except for the google one.

**Comment by sereneblue** [comment] 2020-05-10 22:26
@Keraldi This was a bug with iframes and whitelist handling. It has been fixed in v0.20.5.

@thelmexx Google does some funny things with the Date object that cause the timezone spoofing implementation to break. I've added Google Drive and Google Docs to a permanent whitelist in v0.20.5.

**Closed by sereneblue** 2020-05-10 22:26 UTC
