### ISSUE TITLE
Non-FF profiles cause HMTL5 audio to be distorted

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#127] opened 2019-01-08 22:05 UTC
- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

## Expected Behavior
Chameleon does not interfere with the quality of html5 videos.

## Current Behavior
On some websites using html5 players, audio is distorted.Disabling chameleon fixes the problem. Weirdly this doesn't happen on all sites using html5 audio. Even more weirdly it seems that it is one of the spoofed presets that it is causing issue. 

After some testing (results below) my conclusion is that it is not chameleon per se the issue, but when chameleon uses a profile which is not FF. 

- Chrome 71 (Win 7)  DISTORTED AUDIO
- Chrome 71 (Win 8) DISTORTED AUDIO
- Chrome 71 (Win 8.1) DISTORTED AUDIO
- Chrome 71 (Win 10) DISTORTED AUDIO
- Edge 19 (Win 10) DISTORTED AUDIO 
- Firefox 64 (Win 7) AUDIO OK
- Firefox 64 (Win 8) AUDIO OK
- Firefox 64 (Win 8.1 AUDIO OK
- Firefox 64 (Win 10) AUDIO OK
- Firefox 60 ESR (Win 7) AUDIO OK
- Firefox 60 ESR (Win 8.1) AUDIO OK
- Firefox 60 ESR (Win 10) AUDIO OK

This is a problem not only because distorted audio is a pain.. but also because FF marketshare is quite low...so users can't just stick to FF as spoof because others cause issues with audio.

Note: Seems that FF is notorious for causing distorted audio on linux (so it appears from the many results on google), but I don't think this is a FF issue, more like a chameleon one as when I disable it, audio works fine.

## Context (Environment)
Firefox 64, 64bit Linux, Lubuntu 16.04.3

## WEBSITES AFFECTED:
- Several websites using html5 to reproduce audio (dailymotion is a case Iremember).
- YouTube in my experience is never affected
- Websites using flash seems not to be affected.

Any help?

**Comment by sereneblue** [comment] 2019-01-09 00:02
Thanks for finding this bug! I've also encountered this issue but didn't think Chameleon was the cause (Linux user). I'll look into this and will hopefully find a fix soon.

**Comment by sereneblue** [comment] 2019-01-15 01:52
This issue happens when you change the user agent to a desktop browser that isn't Firefox. I was able to replicate the distorted audio issue on Dailymotion by changing the user agent by using the general.useragent.override about:config option. What other sites are causing issues for you? Dailymotion isn't showing any errors in the console so its really difficult to find a fix.

**Comment by WPFilmmaker** [comment] 2019-01-15 14:23
cough cough.. xvideos.com has the same issue too ...cough cough... (NSFW).

**Comment by WPFilmmaker** [comment] 2019-03-16 13:19
@sereneblue Do you have any updates on this? Accidentally I was able to replicate the bug also with User-Agent Switcher by Alexander Schlarb (https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/) which I was testing for #148.

So it seems that FF distorts audio on certain HTML5 videos when UA is faked...

Could you try to reproduce this with User-Agent Switcher?

**Comment by sereneblue** [comment] 2019-03-16 22:07
I mentioned earlier in this issue that a simple user agent change can trigger the distorted audio. So, it's probably the content that's being served that's causing issues. I'm still not sure what's the root cause. I will probably open a bug on Bugzilla.

**Comment by sereneblue** [comment] 2019-05-07 23:31
There is a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1545847) open on the issue tracker. Since this seems to be a Firefox problem rather than a Chameleon one, I'll be closing this issue.

**Closed by sereneblue** 2019-05-07 23:31 UTC
