### ISSUE TITLE
Twitter animation/video not played

### ISSUE THREAD

**Issue by slrslr** [sereneblue/chameleon#255] opened 2019-10-31 10:56 UTC
- [-] I hope i am running the latest version of Chameleon. Mine is v0.12.19
- [-] I checked to make sure that this issue has not already been filed

## Expected Behavior
play videos on twitter

## Current Behavior
not playing, instead when clicking the video image (try at https://twitter.com/jack/status/1189634360472829952), it then show some grey placeholder instead of video playback

## Relevant settings
[exported c0nfig](https://privatebin.net/?61266cd72d455b7b#6qHuWmXHJSbGHtqFE4HGV9J3eztbL93K65jgbkkcdgNi) (p@ssw0rd: ab)
note that twitter is whitelisted, because the issue stopped when i whitelisted it.

## Context (Environment)
up to date Firefox beta (71.x) on Windows 10

**Comment by sereneblue** [comment] 2019-11-03 01:20
Hi @slrslr,

I'm looking into this issue. If I recall correctly Twitter has been a bit problematic for Firefox users, usually because of tracking protection. However, since you're able to resolve this issue using the whitelist, it seems the cause lies elsewhere. It's probably an issue with profile spoofing.

**Comment by WPFilmmaker** [comment] 2019-12-31 14:18
@sereneblue @slrslr is this still relevant? I tried playing a video on twitter and with latest chameleon it works. The only issues is the annoying audio distortion due to firefox's bug....I assume slrslr you experience it too right?

**Comment by slrslr** [comment] 2019-12-31 15:36
@WPFilmmaker hi, i just removed Twitter from the whitelist and tried to play a few videos and i think that it plays without problem. I do not "see" any issue with sound. (having Firefox beta - 72.0) also images displays OK. For me the problem fixed.. thank you

**Comment by WPFilmmaker** [comment] 2019-12-31 16:13
@slrslr glad it works. So you have no been affected by this: https://github.com/sereneblue/chameleon/issues/127 ? If so it is great! I am on FF71 and still have it but maybe they fixed in the next version.

**Comment by slrslr** [comment] 2019-12-31 16:27
@WPFilmmaker the issue submitter is on Linux, i am on Windows with Firefox and "Ungoogled Chromium" and i do not remember having audio problem. Should this issue be closed (i no longer see the issue on WIn10 and FF beta 72.0)?

**Comment by WPFilmmaker** [comment] 2019-12-31 16:44
@slrslr gotcha! I think you can close this as it is fixed, even if it closed someone can write and can be reopened in the future.

**Closed** 2019-12-31 16:47 UTC
