### ISSUE TITLE
Youtube and other sites respond slowly or completely broken

### ISSUE THREAD

**Issue by quiet23** [sereneblue/chameleon#349] opened 2020-05-04 06:58 UTC
Chameleon 0.20.2.1

## Expected Behavior
Youtube to open and work properly without a significant delay.

## Current Behavior
Youtube either hangs for 10-20 seconds before executing the requested action (switch to full screen, show comments, even clicking on a link to another video) or freezes completely (loading process seems to be unfinished in the case). Firefox is fully loading 1 processor core (25% load, I have 4-core Phenom II X4) during the hangs.
Sometimes parts of the page are missing, sometimes everything is showing up.
Disabling Chameleon completely fixed the problem, Youtube begins to work fast and reliable.

## Relevant settings
Youtube is whitelisted in Chameleon, default whitelist profile is Real Profile. Firefox config is [here](https://pastebin.com/9xxJymUP).

## Context (Environment)
Firefox 75.0 under Windows 8.1 64-bit.

The bug also appears on https://gisanddata.maps.arcgis.com/apps/opsdashboard/index.html#/bda7594740fd40299423467b48e9ecf6 , the page _never_ loads completely. I remember some other pages to behave the same way, but cannot recall a URL.

<img width="800" alt="firefox_2020-05-04_10-50-18" src="https://user-images.githubusercontent.com/30497731/80942268-6ccb7b00-8df5-11ea-85b7-35912f13c605.png">

**Comment by WPFilmmaker** [comment] 2020-05-04 18:46
I can't reproduce this on my linux system and i have the same Firefox and chameleon version, so maybe windows only?

**Comment by sereneblue** [comment] 2020-05-05 03:57
Hi @quiet23, I believe the issue is caused by the fingerprint detection panel. I've removed it from Chameleon and was able to load the arcgis URL you linked. I wasn't able to replicate your issue with Youtube but I suspect it may also be caused by the fingerprint panel. Can you let me know if v0.20.3 resolves your issues?

**Comment by quiet23** [comment] 2020-05-05 06:54
Hello @sereneblue, version 0.20.3.1 allows Youtube to be responsive, thank you very much. Arcgis page, however, almost never completes loading, and even when it appears to be loaded, makes Firefox consuming 1 processor core indefinitely. Whitelisting the page eliminates the problem though.

<img width="800" alt="Firefox on Windows 2020-05-05_09-57-01" src="https://user-images.githubusercontent.com/30497731/81040119-49670580-8eb3-11ea-8a2a-102c9ed53ce1.png">

@WPFilmmaker, I tried to copy the Firefox profile from Windows to Ubuntu 16.04.1
 and was able to reproduce the issue with arcgis there as well with both 0.20.2.1 and 0.20.3.1 versions. Youtube, while always successfully loaded and even usable, consumed 100% processor (2 cores) indefinitely with 0.20.2.1. The issue has mysteriously disappeared though after some experimenting with disabling/enabling different addons and does not come up even after extracting the affected profile to /home/<user>/.mozilla/firefox again.

<img width="800" alt="Firefox on Linux 2020-05-05_10-24-12" src="https://user-images.githubusercontent.com/30497731/81040084-39e7bc80-8eb3-11ea-9763-ed2cb032ba57.png">

**Comment by WPFilmmaker** [comment] 2020-05-05 10:34
OK I am officially dumb:D when I tried I had chameleon disabled because it breaks whatsappweb. I tried it enabled and youtube is noticeably slower and also that coronavirus website is almost unbrowsable (to be honest even normally it is kinda sluggish to load because of js i think). So i can confirm also on linux:)

**Comment by sereneblue** [comment] 2020-05-06 03:45
@quiet23 @WPFilmmaker Can you post your settings?

**Comment by quiet23** [comment] 2020-05-06 04:37
@sereneblue, [chameleon_1588739519664.json.zip](https://github.com/sereneblue/chameleon/files/4584816/chameleon_1588739519664.json.zip)

**Comment by sereneblue** [comment] 2020-05-12 22:52
@quiet23 It seems that the ArcGIS issue is because of timezone spoofing. This is related to #345.

**Comment by quiet23** [comment] 2020-05-13 05:43
@sereneblue, thank you so much, disabling timezone spoofing helped with arcgis.

**Comment by sereneblue** [comment] 2020-05-19 03:17
@quiet23 Timezone spoofing has been fixed in v0.20.8. You should be able to load the ArcGIS now (with timezone spoofing) without issues.

**Closed by sereneblue** 2020-05-19 03:17 UTC
