### ISSUE TITLE
Last update broke Weather.com

### ISSUE THREAD

**Issue by linksky56** [sereneblue/chameleon#396] opened 2020-06-19 18:30 UTC
Hello,

Latest update (Version 0.20.15.1)  breaks weather.com. https://weather.com/

The Today, Hourly and 10Day forecast pages don't load properly.
The Weekend, Monthly and Radar forecast pages do load correctly. Go figure?

Tried to whitelist weather.com and that didn't work.

When i disable Chameleon using icon or when i install old version (Version 0.20.14.1), all the pages for weather.com load properly.

Hope you can fix the glitch, until then I'll just continue using Version 0.20.14.1 (which has been working flawlessly). 

Thanks,
linksky56

**Comment by sereneblue** [comment] 2020-06-20 17:12
Hi @linksky56,

This was caused by a regression introduced in v0.20.15. This should be resolved in the next update.

**Closed by sereneblue** 2020-06-20 17:12 UTC

**Comment by linksky56** [comment] 2020-06-21 02:46
Hi @sereneblue 

That was fast!!.....works perfect again.
Thank you!
