### ISSUE TITLE
Seems to be a lot of issues with v0.20

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [sereneblue/chameleon#367] opened 2020-05-12 01:20 UTC
Was it tested for more than 5 minutes before release?

Wouldn't it be easier to revert to the old UI (as some have [requested](https://github.com/sereneblue/chameleon/issues/343)) than fix all the new bugs?

At least revert until the new UI has been THOROUGHLY VETTED  by beta testers?

I do appreciate the effort and time put into maintaining it, but it has also cause ME a lot of aggravation and wasted time lately.

**Comment by sereneblue** [comment] 2020-05-12 02:36
@GitTheHellOutaHere There was an alpha build of Chameleon v0.20.0 available for some time. #291 
Most of the

**Comment by sereneblue** [comment] 2020-05-12 03:14
@GitTheHellOutaHere 

There was an alpha build of Chameleon v0.20.0 available for some time (#291). I admit there were a few bugs in some specific features. Automated testing (work in progress) would have caught some of them but not all. For example, the issue you were experiencing with #366 would not have been caught by testing. Some of these bugs will go undetected until a user lands on a site that breaks and reports the issue on Github.

The issue you linked about the old UI is not an issue with Chameleon rather than a user stating a preference for the old UI. I left it open to collect more feedback on areas where the current UI can be improved.

Most of the new issues were caused by the fingerprint panel that was removed in v0.20.3. The implementation of that feature was too brittle which caused sites to break a lot. Timezone spoofing seems to be the other major issue but that's to be expected considering what Chameleon does to achieve that. It was an ongoing issue with v0.12.x and will perhaps always be an issue.

Outside of timezone spoofing, the only major outstanding issue seems to be using non-Firefox profiles on sites that use Chrome specific APIs/features. Whitelisting a site is the solution for that. There was an issue with some profiles that used fake plugins (#366) but that will be addressed in an update later today (v0.20.6).

Most of the issues were addressed by simply removing the fingerprint detection panel so there's no reason to go back to v0.12.x. Fortunately, Chameleon will be getting few, if any, new features in the near future so I can focus on fixing bugs.

**Comment by WPFilmmaker** [comment] 2020-05-12 15:36
sereneblue does an amazing job with chameleon, I think the issues encountered (by myself as well) are due to the poor beta testing from the community. I don't know how many tested the beta (I didnt due to lack of time) but it seems not many.  Privacy extensions do break websites and sometimes break themselves as well because they are complex. We can all hope that more efforts will be put in bugs reporting.

**Closed** 2020-06-04 02:15 UTC
