### ISSUE TITLE
Unresponsive webpages

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [sereneblue/chameleon#427] opened 2020-07-30 03:51 UTC
Lately I've been experiencing unresponsive webpages on two sites caused by Chameleon.

Even after I uncheck every option, return things to their default settings, turn off tracking protection, allow all websockets, allow all cookies AND switch to real profile, the problem persists.

Only after disabling Chameleon in the Addons window do those pages function properly again.

On Target.com all I have to do is go to the homepage and wait 10 seconds for the yellow bar to appear.

![Target slowdown](https://user-images.githubusercontent.com/15519219/88878563-c2a69800-d217-11ea-8551-489b32d93b2c.jpg)

On Craigslist.com it only happens when posting/reposting ads, whether I'm logged in or not. Refresh the posting page before the ad is published and wait 10 seconds for the yellow bar to appear. Press the **Stop It** button,  refresh the page, wait another 10 seconds and the bar appears again. AFAICT Craigslist has no 3rd party cookies, analytics or other tracking garbage - just  a login cookie.

![Craigslist slowdown](https://user-images.githubusercontent.com/15519219/88878573-c76b4c00-d217-11ea-9e3d-c8017d9d599b.jpg)

Firefox 78.0.2
Chameleon 0.20.21-rc1

**Comment by sereneblue** [comment] 2020-07-31 02:05
@GitTheHellOutaHere Can you check to see if there are any errors displayed in the developer console when you visit those sites? It might be an implementation issue with something, although Chameleon doesn't modify much when there aren't any options selected. I've read some users have experienced issues with FF78 so I'm not sure if it's because of FF or Chameleon even though you're able to reproduce the issue.

**Comment by GitTheHellOutaHere** [comment] 2020-07-31 13:21
**_GOOD NEWS!_** (I think).

As I was copying the Console messages, I found AdGuard mentioned there and wondered why.

I had previously disabled the AdGuard extension when diagnosing this issue, but I had not quit the AdGuard app.
And I didn't think about it being active because it's hidden in my menu bar.

So I tried again  - disabling the extension had no effect. BUT, when I quit the app the problem disappeared.
Now I wonder why disabling Chameleon with the AdGuard app running also fixed the issue?

**Comment by sereneblue** [comment] 2020-08-02 03:39
@GitTheHellOutaHere That's an interesting find. I'm not sure how Chameleon could be affecting the AdGuard app; it shouldn't. Can you post the console messages? There may be something useful there.

**Comment by GitTheHellOutaHere** [comment] 2020-08-02 04:26
This is what's shown after the page is refreshed:

GEThttps://post.craigslist.org/k/wpJW63XU6hGC9txIjENzVw/Ehs5Y?s=edit
[HTTP/1.1 200 OK 944ms]

This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. Ehs5Y
GEThttps://www.craigslist.org/js/postingform-concat.min.js?v=d0b610110e8d3854348ad323f116d72c
[HTTP/1.1 304 Not Modified 606ms]

GEThttps://www.craigslist.org/js/leaflet-concat.min.js?v=4c56f70c4eb7294c8ffeb1d8fdcf4704
[HTTP/1.1 304 Not Modified 609ms]

GEThttps://www.craigslist.org/js/compatibility2.min.js?v=fd630767e654dff573113fe397b9a60d
[HTTP/1.1 304 Not Modified 614ms]

GEThttps://www.craigslist.org/js/general-concat.min.js?v=2111bc640b19fbe02a5307259bd7cbcf
[HTTP/1.1 304 Not Modified 615ms]

GEThttps://www.craigslist.org/js/postings-concat.min.js?v=2d4831dedac3b38ffbd3e225ccfb1a30
[HTTP/1.1 304 Not Modified 620ms]

GEThttps://local.adguard.org/?ts=1596341373834&type=content-script&dmn=post.craigslist.org&css=1&js=1&gcss=1&rel=1&rji=1&stealth=1&uag=TW96aWxsYS81LjAgKFdpbmRvd3MgTlQgMTAuMDsgV2luNjQ7IHg2NDsgcnY6NzguMCkgR2Vja28vMjAxMDAxMDEgRmlyZWZveC83OC4w&trref=aHR0cHM6Ly9wb3N0LmNyYWlnc2xpc3Qub3JnLw==
[HTTP/1.1 200 OK 149ms]

GEThttps://local.adguard.org/?ts=1596341373834&name=AdGuard%20Popup%20Blocker&name=AdGuard%20Assistant&name=AdGuard%20Extra&type=user-script
[HTTP/1.1 200 OK 171ms]

GEThttps://post.craigslist.org/favicon.ico
[HTTP/1.1 200 OK 0ms]

Deprecated include of L.Mixin.Events: this property will be removed in future releases, please inherit from L.Evented instead. S.extend/<@https://www.craigslist.org/js/leaflet-concat.min.js?v=4c56f70c4eb7294c8ffeb1d8fdcf4704:1:3276
S.extend@https://www.craigslist.org/js/leaflet-concat.min.js?v=4c56f70c4eb7294c8ffeb1d8fdcf4704:1:3294
@https://www.craigslist.org/js/leaflet-concat.min.js?v=4c56f70c4eb7294c8ffeb1d8fdcf4704:1:175256
leaflet-concat.min.js:1:3141
GEThttps://www.craigslist.org/static/www/localStorage-b2c30773fe82c3d5e475613ad0f725fa9ab277fb.html
[HTTP/1.1 200 OK 0ms]

GEThttps://www.craigslist.org/js/bfp3-concat.min.js
[HTTP/1.1 304 Not Modified 97ms]

GEThttps://www.craigslist.org/styles/images/ui-icons_888888_256x240.png
[HTTP/1.1 304 Not Modified 96ms]

Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://www.craigslist.org’) does not match the recipient window’s origin (‘https://post.craigslist.org’). localStorage-b2c30773fe82c3d5e475613ad0f725fa9ab277fb.html




**And then if I just wait almost a minute, the yellow bar disappears and the page becomes responsive again  and these entries show up:**

Blocked https://post.craigslist.org/k/wpJW63XU6hGC9txIjENzVw/Ehs5Y?s=edit from extracting canvas data because no user input was detected. bfp3-concat.min.js:1:10490
Blocked https://post.craigslist.org/k/wpJW63XU6hGC9txIjENzVw/Ehs5Y?s=edit from extracting canvas data because no user input was detected. Ehs5Y:218:22
Failed to create WebGL context: WebGL is currently disabled. bfp3-concat.min.js:1:18887
Failed to create WebGL context: WebGL is currently disabled.

**Comment by sereneblue** [comment] 2020-08-03 02:16
@GitTheHellOutaHere Hm, perhaps the AdGuard app is interacting with the extension. I noticed you're using `Chameleon 0.20.21-rc1` which is the dev build of Chameleon. It allows external apps to interact with it, so I wonder if there's something going on there. I believe the AdGuard app injects a content script when making the call to `local.adguard.org`. Can you replicate the issue with the stable version of Chameleon from AMO?

**Comment by GitTheHellOutaHere** [comment] 2020-08-03 02:18
I was unaware there was another version of Chameleon.
I got this off Mozilla and didn't see another. Link?

**Comment by sereneblue** [comment] 2020-08-03 03:06
@GitTheHellOutaHere The dev build is located [here](https://github.com/sereneblue/chameleon/releases). v0.20.21-rc1 should be 0.20.21.1. You can verify this by exporting your settings and checking the version. It's not listed on [AMO](https://addons.mozilla.org/en-US/firefox/addon/chameleon-ext/versions/) because it's self-hosted on Github so I'm a bit confused how you have it installed.

**Comment by GitTheHellOutaHere** [comment] 2020-08-03 11:55
I may have been mistaken.
I _thought_ I got it from the Add-ons site where I got all my other extensions.

But perhaps I read about Chameleon and then Googled it and followed the Github link.

Evidently Mozilla recognizes the Dev. version as the correct extension, because when I go to the AMO page there's no option to install the release version. Looks like I'll have to uninstall the Dev. version first.

Yup, as soon as I uninstalled it I was able to add it.

_Huh_ - all my settings were saved! 😎
I expected to have to redo them all. Is that because I didn't close/reopen Firefox?

**Comment by GitTheHellOutaHere** [comment] 2020-08-03 11:58
Problem remains after switching to v0.20.23. 😖

**Comment by sereneblue** [comment] 2020-08-04 03:46
Can you post your settings? I don't think there's much I can do until I can reproduce this issue.

**Comment by GitTheHellOutaHere** [comment] 2020-08-04 12:11
1. I didn't know you were still interested since it seems to be an AdGuard issue.

2. I told you I reset ALL settings to unchecked/default/allow everything/real profile etc.

**Comment by GitTheHellOutaHere** [comment] 2020-08-04 12:19
Just installed Chameleon 0.20.24 and nothing changed with Craigslist.

**Comment by GitTheHellOutaHere** [comment] 2020-08-04 13:16
And this is even weirder.

I went [here](http://browserspy.dk/useragent.php)  to see what is revealed about my user agent.

With Real Profile selected, that site shows the wrong UA. I had disabled Privacy Settings extension and quit AdGuard before  checking , since they can both conceal the UA.

![BrowserSpy 1](https://user-images.githubusercontent.com/15519219/89298127-6a76f800-d654-11ea-836e-e42ef104f9a1.jpg)


Only after disabling Chameleon does it show the correct UA.

![BrowserSpy 2](https://user-images.githubusercontent.com/15519219/89298142-6e0a7f00-d654-11ea-922c-f5afaea3546d.jpg)

**Chameleon should not conceal the UA when Real Profile is selected.**

**Comment by sereneblue** [comment] 2020-08-05 01:01
@GitTheHellOutaHere It looks like RFP is enabled; check about:config. If you modify preferences there, Chameleon doesn't know. That should be addressed in the next update.

**Comment by GitTheHellOutaHere** [comment] 2020-08-05 12:57
If you're referring to blocking fingerprinting in Firefox prefs, then yes - it's definitely enabled.

I hadn't noticed before that enabling RFP in Chameleon or Privacy Settings does NOT enable it in the prefs. Why is that? Anyone enabling that option in extensions clearly wants to block fingerprinting.

They also don't have options to block miners - that's another important thing that must be checked in the prefs. Does Chameleon ignore those because they aren't privacy-related?

What's your thoughts on using Chameleon with Privacy Settings? Unnecessary or problematic redundancy?

**Comment by GitTheHellOutaHere** [comment] 2020-08-05 16:57
I just answered that last question.
The latest version of Chameleon _does_ conflict with Privacy Settings, making it's settings unusable.

I've been using both together a long time and this is new.
P.S. was last updated in Feb., so it isn't suddenly causing the problem.


With Chameleon enabled, all of P.S.'s settings become disabled.
![Privacy Settings red](https://user-images.githubusercontent.com/15519219/89437371-5555a400-d6fc-11ea-993e-3ce27b7c5e6c.jpg)

With Chameleon disabled, all the settings return to where I had them.
![Privacy Settings green](https://user-images.githubusercontent.com/15519219/89437464-7918ea00-d6fc-11ea-9fac-f5444892c970.jpg)

And this is odd: Chameleon, P.S. and FF prefs were all set to block all 3rd party trackers - have been for a long time.

But now with Chameleon enabled, P.S. switches to ACCEPT ALL cookies even though the prefs still show all 3rd party cookies are blocked.
![FF prefs](https://user-images.githubusercontent.com/15519219/89438588-dbbeb580-d6fd-11ea-9eb2-41339a27b910.jpg)

And the websockets setting in Chameleon no longer sticks - it reverts to ALLOW ALL every time.
Change it to a block setting, switch to Injection tab and then back, and the setting has reverted to ALLOW ALL.
Oddly it does not change when switching to Cookie tab.

Same goes for Screen Size settings now.
Change it to something, then switch to Standard tab & back to Injection tab and it's back to Default.
But Cookie tab has no effect on it.

I think 0.20.24 is a regression.

**Comment by GitTheHellOutaHere** [comment] 2020-08-05 17:08
I found another website that becomes unresponsive with Chameleon & AdGuard running.
Disable either one and it's fine.

https://www.techsmith.com/

**Comment by GitTheHellOutaHere** [comment] 2020-08-10 02:31
Well this is just nuts!
Today the Websockets and Screen Size settings are staying put.

Chameleon is still royally interfering with Privacy Settings, though.

**Comment by sereneblue** [comment] 2020-08-10 23:24
@GitTheHellOutaHere Sorry I didn't get a chance to respond to you sooner, I've been a bit busy lately.

Ideally, two extensions shouldn't have control over the same setting. This can cause issues. I'm going to try to find a way to allow users to opt-in/opt-out of allowing Chameleon to manage those settings.

There is a bug with the UI so the displayed value may not be correct. I'll try to release an update by the end of the week so that the displayed value is correct. 

> What's your thoughts on using Chameleon with Privacy Settings? Unnecessary or problematic redundancy?

With Chameleon enabled, Privacy Settings is redundant. I can add some additional preferences (like hyperlink auditing) if necessary.

It's odd that the screen size settings are being changed. Not sure why there are issues related to it. Might be a UI issue if spoofing still works.

I'll look into the URL you provided to try to reproduce the issue with AdGuard.

**Comment by GitTheHellOutaHere** [comment] 2020-08-13 23:33
I'd have preferred reverting to the last version over waiting for a new one.
Definitely something wrong with the UI, because the settings wont stay put again (still).

I discovered this, though:

If I open the Options tab, Screen Size is where I set it; Good.
But then I look in the Standard tab and go right back to the Injection tab, and Screen Size is default again.

Close Chameleon's window and go back to the Injection tab, and Screen Size is correct again.

**Comment by sereneblue** [comment] 2020-08-17 01:48
@GitTheHellOutaHere There were a few issues with the UI that should be resolved in v0.21.0. There is also a new feature that allows you to remove the `privacy` permission if you don't want Chameleon to control the privacy preferences (tracking protection, cookie settings, etc). 

Disabling an extension that controls some preferences does reset it. That's how Firefox handles it, so there's not much I can offer there.

**Comment by GitTheHellOutaHere** [comment] 2020-08-17 11:43
I gave up on Chameleon and went back to using just Privacy Settings.
But I enabled Chameleon again to try v0.21.0, and when I did it updated to 0.21.0.1

But there appears to be another UI glitch because the Chameleon window shows 0.21.0, **not** 0.21.0.1.

And according to the [extension page](https://addons.mozilla.org/en-US/firefox/addon/chameleon-ext/versions/) there was no 0.21.0.

![Chameleon 0 21 0](https://user-images.githubusercontent.com/15519219/90391803-44524e80-e07d-11ea-9293-94b0b6feef64.jpg)

![Chameleon 0 21 0 1 prefs](https://user-images.githubusercontent.com/15519219/90392052-b62a9800-e07d-11ea-99ba-1d984d69a59d.jpg)



I don't see the new setting you told me about via email:

> There were a few issues with the UI that should be resolved in v0.21.0. There is also a new feature that allows you to remove the privacy permission if you don't want Chameleon to control the privacy preferences (tracking protection, cookie settings, etc).

However, I see little point in using Chameleon if you disable its privacy protections.
Maybe dev's have more use for things like Spoof X-Forwarded-For/Via IP, Referrer X Origin Policy and Referrer Trimming Policy as well as needing to change User Agent more frequently than a casual user.

Chameleon's a bully - even when P.S. is enabled first and controlling the settings, Chameleon takes over in prefs.
and P.S. immediately becomes useless and its controls turn red.

**Comment by sereneblue** [comment] 2020-08-17 22:13
@GitTheHellOutaHere The version name isn't a UI bug. Only the first three numbers are really significant. The last bit is only used to identify the dev/stable release. Generally, 0 is for a dev build and 1 is for stable (or 1/2). 

The new setting is found in the dashboard (the gears icon). It disables the privacy permission which is used to control settings like RFP, tracking protection, WebRTC, etc. All of the other features in Chameleon still work; you just won't be able to modify most of the preferences on the standard/cookie tab.

**Comment by GitTheHellOutaHere** [comment] 2020-08-18 01:33
But there's no way to tell if an incremental update has occurred without looking in the Extensions page.

I'd briefly looked at the Options page but nothing new caught my eye.
Now I see it there at the bottom and it does indeed relinquish control, which allows Privacy Settings to take over the duty of managing tracking content and cookies. 

I didn't expect Chameleon to stop disabling WebRTC as part of that change, but P.S. has that covered.

**Comment by sereneblue** [comment] 2020-08-18 02:26
@GitTheHellOutaHere Stable Chameleon releases don't have incremental updates (that only change the last number). The dev/stable builds share the same addon id (in hindsight, this may have been a mistake) and the only way to allow both of them to coexist is to give a unique version number to each build. Generally it's 0/1 for the last number, but in some rare cases, I may find something missing/broken in the dev build so the last number will be incremented until there is a final dev build. The stable release is +1 to the final dev build version. Any update to the stable version of Chameleon will visibly increase the version number (v0.20.0 => v0.20.1 or v0.21.0) so users should know that there was an update.

WebRTC falls under the `privacy` API so when the permission is removed, Chameleon can no longer manage it.

**Closed** 2020-11-26 17:58 UTC
