### ISSUE TITLE
browserleaks.com Canvas Fingerprinting test failed when timezone spoof Ip mode enable

### ISSUE THREAD

**Issue by tmxd09887** [sereneblue/chameleon#294] opened 2020-02-27 10:40 UTC
# Prerequisites

Please use issues for bugs only! Answer the following questions for yourself before submitting an issue: **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [ ] I am running the latest version
yes
Chameleon Dev v0.20.0-alpha0
- [ ] I checked the documentation and found no answer
yes
- [ ] I checked to make sure that this issue has not already been filed
yes

## Context (Environment)

firefox 73.0.1,windows10

I just found if I set ip mode to timezone spoof,browserleaks.com Canvas Fingerprinting test failed

Please check the screenshot
![image](https://user-images.githubusercontent.com/730750/75436349-5cc79300-598f-11ea-9d9b-8d0e04c925e1.png)

But, I switch timezone to default or other setting,  it can be tested correcttly

**Comment by sereneblue** [comment] 2020-02-28 00:40
HI @tmxd09887,

Thanks for testing Chameleon v0.20.0. Are you using Canvas Blocker with the profile that you're testing with?

**Comment by tmxd09887** [comment] 2020-02-28 01:56
yes,I installed Canvas Blocker,but disabled when testing

**Comment by sereneblue** [comment] 2020-02-28 04:56
Can you update to v0.20.0-alpha1 (check the releases tab) and post your exported settings? There may be a bug in the IP rules feature that's causing issues; I haven't thoroughly tested it.

**Comment by tmxd09887** [comment] 2020-02-28 05:01
ok
[chameleon_1582866001777.zip](https://github.com/sereneblue/chameleon/files/4265296/chameleon_1582866001777.zip)

**Comment by sereneblue** [comment] 2020-02-29 00:09
Hi @tmxd09887,

Thanks for posting your settings. I've identified the issue is and should have a fix available soon. I hope to release the next version within a few days with a number of bug fixes so this should be resolved in the next update.

**Comment by tmxd09887** [comment] 2020-02-29 01:54
thanks

great job!

**Closed** 2020-02-29 01:54 UTC
