### ISSUE TITLE
"Enable script injection" makes youtube "?disable_polymer=true"

### ISSUE THREAD

**Issue by chameleonuser** [sereneblue/chameleon#189] opened 2019-05-14 13:10 UTC
# Prerequisites

- [+] I am running the latest version
- [+] I checked the documentation and found no answer
- [+] I checked to make sure that this issue has not already been filed

## Expected Behavior
Normal

## Current Behavior
Problem detected on may 13 or so, nothing was changed in my settings, YT was already whitelisted before and worked fine. SUDDENLY it started adding "?disable_polymer=true" to every URL, so _polymer_ got disabled.
I've tried disabling every option within Chameleon, but only unchecking script injection makes YT act as expected.

## Relevant settings
N/A

## Context (Environment)
FF 66.0.5 as current
Chameleon 0.12.2

**Comment by WPFilmmaker** [comment] 2019-05-14 20:18
On 66.0.5 (64-bit) Linux and  Chameleon 0.12.2 I am unable to reproduce this. Youtube Urls are normal.

**Comment by sereneblue** [comment] 2019-05-16 00:07
This was changed in v0.12.2. In the next update this will be fixed so that it only disables polymer when using a desktop Chrome profile as your default spoof profile or whitelist profile, if you somehow happen to use it with youtube in the whitelist.

**Comment by DPTJKKVH** [comment] 2019-05-21 21:41
Bug is still present in 0.12.4

I neither use chrome as my current fake profil nor do I use it as a whitelist profile nor do I have youtube.com whitelisted. Still chameleon appends disable_polymer=true to all youtube uris

**Comment by sereneblue** [comment] 2019-05-22 02:42
@DPTJKKVH Thanks, I can confirm that this bug is still present in the latest version. I'll have this fixed in the next update.

**Closed** 2019-05-24 00:12 UTC

**Comment by DPTJKKVH** [comment] 2019-08-11 09:13
I'm on Firefox 68.0.1 (64 bit) and I do not fake my UA to be Chrome. In fact I do not use the Agent switcher of Chameleon at all. Still every time I go on youtube it adds an `&disable_polymer=true` at the end.

Chameleon settings:
Profile: Real Profile
Headers: Spoof Accept & Accept encoding headers + Accept Language EN-US
Options: Enable Script Injection + Websockets Block All

**Comment by sereneblue** [comment] 2019-08-11 23:52
@DPTJKKVH I've identified the issue, the next update should improve this. It's still not as nice as I'd like because things get a little messy when you're switching between profiles while using Youtube. Hopefully Google fixes Youtube soon.

**Comment by DPTJKKVH** [comment] 2019-08-12 08:04
@sereneblue That was quick! I will test it as soon as the new version gets released. If I run into any issues I will report them here.

Thanks 👍
