### ISSUE TITLE
chameleon breaks some more sites 

### ISSUE THREAD

**Issue by jahnson** [sereneblue/chameleon#239] opened 2019-09-09 20:22 UTC
Using 0.12.13

Various web sites have stopped working in the last ~2 weeks.  

Youtube does not work correctly (did before), The video is larger than the available space.  I think because screen size & window size spoofed to 1920 x 1080, so part of the video is outside of my window.  I reduced the spoof to 1366 x 768, but now I have a video window smaller than the space available.  
This problem appeared earlier, then it went away  (the video size appeared to be correct despite the larger spoof) and now it is back.  

Apart from youtube, some other sites will no longer work.  My bank, for example, which shall remain nameless.  Also this one: 
https://www.sony.nl/electronics/ifa?cpint=PDP_GLOBALMODULE_IFA2019OOFM_4932
does not display graphics until I disable chameleon.  In each case disabling chameleon results in the web site working again.  

I have not changed other chameleon settings recently.  In fact, I changed them according to sereneblue's suggestions after the previous episode of web sites that would not display.  

Using FF 69.0 (this problem also appeared under 68.0.x), W7-64.  

Thank you

**Comment by sereneblue** [comment] 2019-09-12 02:31
Hi @jahnson,

Spoofing the screen resolution will cause some sites to break, that's what the whitelist is for. I strongly recommending adding Youtube to it because Youtube is a broken site on Firefox with other user agents. I've tried using the polymer trick but it gets tricky when you're going through a playlist. 

For your bank site, I won't be able to offer much help if I don't know what it is, however, you can try following the instructions [here](https://github.com/sereneblue/chameleon/wiki/Debug) to see if there's an error that could help me debug the issue.

Can you post your exported settings? I'm not sure what's causing the issue for you on the Sony site.

**Comment by jahnson** [comment] 2019-09-19 20:50
The bank site is working again at this moment (after it did not work on two separate days), though it produces a number of yellow warnings in the Developer Console.  

On the Sony site I get the follow error message in the Developer console: 

NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable. sonymobile-21b398028af8344f6e27b4cc4c662a83.js:14

**Comment by jahnson** [comment] 2019-09-19 21:10
for video, perhaps a better solution is to use hooktube or invidio.us

**Comment by sereneblue** [comment] 2019-09-20 02:34
> The bank site is working again at this moment (after it did not work on two separate days), though it produces a number of yellow warnings in the Developer Console.
> 
> On the Sony site I get the follow error message in the Developer console:
> 
> NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable. sonymobile-21b398028af8344f6e27b4cc4c662a83.js:14

Are you using v0.12.15? There was an issue resolved in that update that might have been the cause of the issues you were experiencing.

Can you post your exported settings? That error message doesn't seem to be related to Chameleon.

**Closed** 2020-04-18 19:34 UTC
