### ISSUE TITLE
Screen Size Spoofing Feature Ceases To Work With Site Bleacher Enabled

### ISSUE THREAD

**Issue by Kraxys** [sereneblue/chameleon#154] opened 2019-03-25 03:05 UTC
## Current Behavior

[Site Bleacher](https://addons.mozilla.org/en-US/firefox/addon/site-bleacher/) is an addon intended to "_remove automatically cookies, local storage and IndexedDBs_".

Apparently Chameleon and Site Bleacher have nothing to do with each other.

But nevertheless, with Site Bleacher enabled, the Chameleon's screen size spoofing feature ceases to work. As soon as I disable Site Bleacher, screen size spoofing works again (tested on browserleaks.com).

I cite this issue in case it would be the symptom of some sort of problem in Chameleon's coding of screen size spoofing feature: 

Indeed, when I disable Chameleon and spoof screen size with the addon [Trace](https://addons.mozilla.org/en-US/firefox/addon/absolutedouble-trace/), there is no more incompatibility problem with Site Bleacher, the screen size get spoofed even with Site Bleacher enabled (tested on browserleaks.com and ip-check.info).

NB: To activate a Trace's Screen Size Spoofing feature comparable to the Chameleon's one: 
In Trace menu goo to **settings**, then click on **Configure** _Screen Resolution Tracking Protection_ then click on **Change selection Method**, click on **Add Common Resolution** (it loads 13 resolutions), then **close** and click on **Enable** _Screen Resolution Tracking Protection_

## Relevant settings

_Script injection_ enabled
_Screen Size Spoofing_ set to 1920x1080 (or whatever value)

## Context (Environment)

Chameleon v0.11.7  FF 66 on W7

**Comment by sereneblue** [comment] 2019-03-26 23:18
Thanks for the descriptive issue. I didn't realize there was another screen spoofing extension available for FF users. I'll take a look at this soon.

**Comment by sereneblue** [comment] 2019-04-07 22:00
I'm having difficulties replicating this issue. Using a new Firefox profile, I installed Chameleon, configured the relevant settings for screen size spoofing and then installed Site Bleacher. The screen size is spoofed on browserleaks. Can you reproduce this issue?

**Comment by sereneblue** [comment] 2019-04-21 03:10
@Kraxys I'm still having difficulties replicating this issue. Can you post your Chameleon settings? If you're able to reproduce the issue, it may be another setting that causing the issues.

**Comment by Kraxys** [comment] 2019-04-22 02:58
> 
> 
> @Kraxys I'm still having difficulties replicating this issue. Can you post your Chameleon settings? If you're able to reproduce the issue, it may be another setting that causing the issues.

I have a hard time with this issue. On my tests it happens one time in 2:
Chameleon + Site Bleacher only, start browser and go on browserleaks -> screen size faked
Open new tab, go on browserleak -> screen size not faked
Open new tab, bo on browserleak -> screen size faked.... An so on.
Tested in successively opening 12 tabs. I got 6 tabs with faked screen size, 6 tabs with true screen size.
 This seems related to the Chameleon profile, because when I reset Chameleon and then only check "script injection", "screen size: profile" and "Profile/widows/ FF ESR 60 W7" this kind of issue doesn't happen.

Here is the Chameleon profile I used:


{
  "headers": {
    "blockEtag": true,
    "disableAuth": true,
    "disableRef": false,
    "enableDNT": false,
    "refererXorigin": 0,
    "refererTrimming": 0,
    "spoofAccept": false,
    "spoofAcceptLang": false,
    "spoofAcceptLangValue": "en-US,en;q=0.5",
    "spoofSourceRef": false,
    "spoofVia": false,
    "spoofViaValue": 0,
    "spoofXFor": false,
    "spoofXForValue": 0,
    "upgradeInsecureRequests": true,
    "viaIP": "",
    "viaIP_profile": "",
    "xforwardedforIP": "",
    "xforwardedforIP_profile": "",
    "useragent": "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0"
  },
  "whitelist": {
    "enabled": false,
    "defaultProfile": "none",
    "urlList": []
  },
  "excluded": {
    "win": [
      true,
      true,
      true,
      true,
      false,
      false,
      false,
      false,
      false,
      true,
      true,
      true,
      false,
      false,
      false
    ],
    "mac": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "linux": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "ios": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "android": [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    "all": [
      false,
      false,
      false,
      false,
      false
    ]
  },
  "settings": {
    "customScreen": "",
    "enableScriptInjection": true,
    "interval": 0,
    "limitHistory": false,
    "minInterval": null,
    "maxInterval": null,
    "notificationsEnabled": true,
    "protectWinName": true,
    "screenSize": "profile",
    "spoofAudioContext": false,
    "spoofClientRects": false,
    "timeZone": "ip",
    "useragent": "win13",
    "useragentValue": "Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0",
    "webSockets": "block_3rd_party"
  },
  "version": "0.11.10"
}

**Comment by sereneblue** [comment] 2019-04-23 00:25
Thanks! After some testing, it looks like the issue was fixed in 7bbe2ec35d310b7f9ef6e401626a244a036928c4.

**Closed by sereneblue** 2019-04-23 00:25 UTC
Labels: bug

**Comment by Kraxys** [comment] 2019-04-26 22:02
> 
> 
> Thanks! After some testing, it looks like the issue was fixed in [7bbe2ec](https://github.com/sereneblue/chameleon/commit/7bbe2ec35d310b7f9ef6e401626a244a036928c4).

Very well! Just tested: The bug is gone :)
