### ISSUE TITLE
Sidebar freezes after enable "Spoof Accept Language"

### ISSUE THREAD

**Issue by Kotoki1337** [sereneblue/chameleon#512] opened 2021-07-02 11:31 UTC
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Current Behavior
This issue appeared after [Chameleon Dev v0.21.22-rc](https://github.com/sereneblue/chameleon/releases/tag/v0.21.22-rc)
[Chameleon Legacy Build v0.21.21](https://github.com/sereneblue/chameleon/releases/tag/v0.21.21) don't have this issue
![动画](https://user-images.githubusercontent.com/35394151/124268165-bfc0cf80-db6b-11eb-9091-77c894aaef6e.gif)

## Context (Environment)
79.0 (64-bit)
86.0.1 (64-bit)

**Comment by sereneblue** [comment] 2021-07-04 19:32
Hi @Kotoki1337,

I've tried to replicate this issue with the latest version and I wasn't able to. I'm not sure if the versions you linked to are correct since they're a bit dated. I believe you're using the IP option for spoofing the accept language which might be the cause of this issue. Can you post export your exported settings? Can you also post the language data returned from visiting this [link](https://geoip-lookup.vercel.app/api/geoip)?

**Comment by Kotoki1337** [comment] 2021-07-05 10:00
``{"success":true,"ip":"103.97.201.31","timezone":"Asia/Hong_Kong","languages":"en-HK,zh-Hans-HK,zh-Hant-HK"}``

Tbh it doesn't seem to be any different than usual. The issue should not cause by here, is there any other debugging method?

**Comment by sereneblue** [comment] 2021-07-05 17:34
> `{"success":true,"ip":"103.97.201.31","timezone":"Asia/Hong_Kong","languages":"en-HK,zh-Hans-HK,zh-Hant-HK"}`
> 
> Tbh it doesn't seem to be any different than usual. The issue should not cause by here, is there any other debugging method?

Thanks, I was able to reproduce the issue using the data provided. It was a bug in the code to find a locale based on the data returned. This should be resolved in the next update.

**Closed** 2021-07-05 23:17 UTC
