### ISSUE TITLE
Add option for spoofing custom screen size

### ISSUE THREAD

**Issue by CarlosEkisde** [sereneblue/chameleon#62] opened 2018-10-07 09:35 UTC
Hi, I think it's a needed option because all resolutions listed produces unique or almost unique fingerprints on https://panopticlick.eff.org/ and the only resolution which produces non-unique results is 1000x600 which is Tor Browser default.

If adding an option for custom spoofing can't be done, I suggest adding that screen size option instead.

Thanks :)

**Comment by Kraxys** [comment] 2018-10-07 21:32
>all resolutions listed produces unique or almost unique fingerprints on https://panopticlick.eff.org/

What y are reporting is weird, because, after testing, I get the following results on my side:
* Spoofing 1366x768:
2.87 bits of identifying information. One in 7.32 browsers have this value. 

* Spoofing 1920x1080:
2.5 bits of identifying information. One in 5.67 browsers have this value.

So many browsers having been tested on Panopticlick have a  screen size of 1366x768 or 1920x1080. So either spoofing choice should not contribute to a  big entropy increase

BTW, I think "being unique" is not really an issue, as soon as you are a **different** unique person each time a site tries to fingerprint you. 
Being "very non unique" is a very difficult goal to achieve. For that, it is mandatory you belong to a big "group of anonymity", ie a  big set of peoples sharing exactly the same characteristics.  A sole extension can't do that. For being "very non unique", the best (and the least) to do  is to use TBB.

**Comment by CarlosEkisde** [comment] 2018-10-07 22:15
I understand what you're saying but I think being non-unique it's equally possible when using regular firefox than TBB, setting the correct options on about:config, as TBB leaks windows size as Firefox does, making the fingerprint almost unique when maximizing the window. So the only way to appear non unique when maximizing is spoof the default TBB resolution in both Firefox and TBB

**Comment by Kraxys** [comment] 2018-10-08 02:35
> I think being non-unique it's equally possible when using regular firefox than TBB

I don't think so (although I don't have an absolute proof): First, a large part of TBB configuration consists precisely in smoothing the profile of TBB user in order they will not be distinguishable each other. And TBB dev are working hard for that, since years...  

Second, consider eg canvas. You can either let it untouched (and you will be fingerprinted easily) or block it, or spoof it. As relatively few peoples are blocking Canvas, doing that can become a fingerprint in itself, and canvas blockade, aggregated  with some other elements, may contribute to build a fingerprint for you. At this point you surely can reply: "_Hey, but TBB is default blocking Canvas_". Sure, but TBB users are using Tor Network too. There are very few people blocking Canvas without using Tor Network... The last solution is to spoof Canvas. But then, the spoofed Canvas is unique, and for not being traceable, you have to change it, at least for each session... but not too often either, because changing Canvas too often may make you distinguishable from the others (you will become, for the sites you visit, "the guy who is changing Canvas each request"). In changing Canvas regularly but not too often, you will be each time unique, but not traceable (at least, not traceable through Canvas), which I think is the most important (as so, your browsing sessions can not be correlated to you).

Being being significantly non unique is an other beast. For achieving some king of "non uniqueness" in adjusting prefs in about:config, you have to choose the same prefs as many people have chosen (by "many", i means the size order of TBB users ; and  there is approximately 2 millions TBB connected at each time). For that you have to know the choices of these "many people". But how? The sole way is to enter in a big anonymity group, and there are not so many such groups... Hence, TBB...

**Comment by sereneblue** [comment] 2018-10-08 03:03
@CarlosEkisde It's _very_ difficult to obtain a non-unique profile. From a practical perspective, if you're using Firefox Multi-Account Containers + uBlock Origin + NoScript/uMatrix + Chameleon + a VPN (if you're not changing IPs, everything you've done is near useless), you should be private enough. 

You _don't_ want to have the same screen resolution as TBB if you're not using Tor. By design, every TBB user should have a very similar fingerprint.

I've added the option to use a custom screen resolution. This should appear in v0.9.0.

Good discussion but I'll be closing this issue soon. :)

**Comment by Kraxys** [comment] 2018-10-08 03:15
So, before you close this thread, I just would like to add  I agree with CarlosEkisde that it would be useful to offer to Chameleon's users the possibility to define custom screen size spoofing (same as  the user may define a custom UA).

**Closed** 2018-10-08 03:18 UTC

**Comment by CarlosEkisde** [comment] 2018-10-08 20:06
Thank you for both of you for the things I have learned and for releasing the new upgrade with this new option =)
